spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 5000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 2000
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 20
        # 连接超时时间（毫秒）
        timeout: 5000

customize:
  lock:
    wait:
      #等待获取锁时间 秒
      time: 3
    lease:
      #保存锁时间 秒
      time: 20

#Redisson 单机模式
redisson:
  singleServerConfig:
    address: "redis://192.168.13.3:6379"
    password: 123456
    clientName: null
    database: 0
    idleConnectionTimeout: 10000
    pingTimeout: 1000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    reconnectionTimeout: 3000
    failedAttempts: 3
    subscriptionsPerConnection: 5
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    connectionMinimumIdleSize: 32
    connectionPoolSize: 64
    dnsMonitoringInterval: 5000
    #dnsMonitoring: false
  threads: 0
  nettyThreads: 0
  transportMode: "NIO"
